//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seq.App.BugReporter.AzureDevOps.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seq.App.BugReporter.AzureDevOps.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating bug in Azure DevOps.
        /// </summary>
        internal static string BUG_CREATION_ERROR {
            get {
                return ResourceManager.GetString("BUG_CREATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Event Id:&lt;/strong&gt; {EventId}&lt;br/&gt;&quot;);
        ///&lt;strong&gt;Level:&lt;/strong&gt; {EventLogLevel}&lt;br/&gt;&quot;);
        ///&lt;strong&gt;Timestamp:&lt;/strong&gt; {EventTimestamp}&lt;br/&gt;&quot;);
        ///&lt;strong&gt;Event Url:&lt;/strong&gt; &lt;a href=\&quot;{EventUrl}\&quot; target=\&quot;_blank\&quot;&gt;Seq event details&lt;/a&gt;&lt;br/&gt;&quot;);
        ///{EventProperties}&lt;br /&gt;&quot;);
        ///&lt;strong&gt;Message:&lt;/strong&gt; {EventMessage}&lt;br/&gt;&quot;);
        ///{EventException}&lt;br /&gt;&quot;);.
        /// </summary>
        internal static string DEFAULT_DESCRIPTION {
            get {
                return ResourceManager.GetString("DEFAULT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SEQ Bug Reporter/{EventLogLevel}] - {EventMessage}.
        /// </summary>
        internal static string DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Azure DevOps bug creation prevented for event id {id} / unique id {uniqueId}.
        /// </summary>
        internal static string DUPLICATE_AZURE_DEVOPS_BUG {
            get {
                return ResourceManager.GetString("DUPLICATE_AZURE_DEVOPS_BUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build bug creation payload.
        /// </summary>
        internal static string FAILED_TO_BUILD_BUG_CREATION_PAYLOAD {
            get {
                return ResourceManager.GetString("FAILED_TO_BUILD_BUG_CREATION_PAYLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate bug description.
        /// </summary>
        internal static string FAILED_TO_GENERATE_DESCRIPTION {
            get {
                return ResourceManager.GetString("FAILED_TO_GENERATE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate bug title.
        /// </summary>
        internal static string FAILED_TO_GENERATE_TITLE {
            get {
                return ResourceManager.GetString("FAILED_TO_GENERATE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (This parameter &lt;i&gt;{0}&lt;/i&gt; is not supported).
        /// </summary>
        internal static string UNSUPPORTED_PARAMETER {
            get {
                return ResourceManager.GetString("UNSUPPORTED_PARAMETER", resourceCulture);
            }
        }
    }
}
